### ISSUE TITLE
Wordpress install fail

### ISSUE THREAD

**Issue by philthane** [zelon88/HRCloud2#26]
**This document is a template for submitting technical issues for HRCloud2.**

Submit issues on Github: https://github.com/zelon88/HRCloud2/issues.

Email issues to: zelon88@gmail.com.

--------------------------------------------------

Hello,

My name is Phil Thane, I'm installing HRCloud2 on a Ubuntu 19.10 macine with PHP 7.3. Using HRCloud 2 version 3.1 Using your instructions here: https://github.com/zelon88/HRCloud2/blob/master/How_To_Install_HRCloud2.txt

I got to the bottom of step 5 and when logging into the server via a browser I see a quick flash of a Welcome page *I think* then an error message:

_Notice!!! HRC2CommonCore27, WordPress was not detected on the server.
Please visit http://yourserver in a browser and configure WordPress before returning or refreshing this page.
OP-Act: Installing WordPress.
ERROR!!! HRC2CommonCore32, WordPress was not detected on the server and could not be installed._

As WP isn't installed I can't configure it. Suggestions?

**Comment by zelon88** [comment]
Thanks for using HRCloud2!

I think it might be the included wordpress.zip package being formatted incorrectly. To confirm this, please navigate to your $ServerRootDir (default is /var/www/html) and check for the existence of a "wordpress" folder. If "/var/www/html/wordpress" exists then you need to copy all the files out of it and move them down one level. So everything in "/var/www/html/wordpress" should go into "/var/www/html" instead.

If that does not work please continue trying things in the order below...

1. Verify that zip is installed by opening a terminal and typing 
`sudo apt-get install zip `

2. Visit https://wordpress.org/download/ and download the latest Wordpress v5.3. 

3. Extract the archive and copy the contents of the "wordpress" folder to "/var/www/html" manually.

4. **If you do not have proper permissions** to extract the "wordpress" folder to "/var/www/html" you must open a terminal and type 
`sudo chown -R YOURUSERNAME:users /var/www/html`
You will now be able to copy files manually.

5. To correct permissions **after running step 4** open a terminal and type 
`sudo chown -R www-data:www-data /var/www/html`


Please let me know how this works out.

**Comment by zelon88** [comment]
Addressed in.....

c9f9f096ffd91a4f60a6f094395a0669c874edb1
https://github.com/zelon88/HRCloud2/commit/c9f9f096ffd91a4f60a6f094395a0669c874edb1

.....and.....

8a2a693852d1461f9e89e3ed9bcdb813de0ee570
https://github.com/zelon88/HRCloud2/commit/8a2a693852d1461f9e89e3ed9bcdb813de0ee570

**Comment by zelon88** [comment]
I'm gonna close this as I haven't heard back, but if you're still having problems feel free to reopen or create a new issue. 

Also per the HonestRepair [Alternative Licensing](https://www.honestrepair.net/index.php/alternative-licensing/) policy, @philthane gets a free BSD 3-Clause license for HRCloud2 for life. Thanks for contributing to the HRCloud2 project!
